spring:
  application:
    name: customer
  profiles:
    active: production

# ACTUATOR INFO
eureka:
  client: ${eureka-client}
application:
  allow-get-customer: ${customer.allow-get-customer}
info:
  app:
    name: customer
    profile: "${spring.profiles.active}"
    version: "0.0.1"
  serverInfo:
    port: "${server.port}"
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true

accounts:
  ribbon:
    eureka:
      enabled: false
      listOfServers: localhost:9999,localhost:9998
server:
  port: 7777